hostname: pi-gw
ssh_user: syh
static_ip: 10.27.0.100/24
static_gatewway: 10.27.0.1
static_routes:
  - dest: 10.8.0.0/24
    gw: 10.27.0.2
  - dest: 172.16.0.0/12
    gw: 10.27.0.2
dhcp:
  pool_start: 10.27.0.128
  pool_end: 10.27.0.253
  lease: 12h

dns_hosts:
  - ip: 10.27.0.1
    name: dlinkrouter
    mac: 6C:19:8F:CC:2E:FB

  - ip: 10.27.0.2
    name: nas
    mac: 00:08:9B:C8:47:4C

  #- ip: 10.27.0.3
  #  name: nas

  - ip: 10.27.0.4
    name: nest-cam
    mac: 18:B4:30:26:02:77

  - ip: 10.27.0.5
    name: pioneer
    mac: 3C:BD:D8:2E:96:C8

  - ip: 10.27.0.6
    name: ipcam
    mac: 00:0D:C5:D9:06:E2

  - ip: 10.27.0.7
    name: squeezebox
    mac: 00:04:20:28:50:85

  - ip: 10.27.0.8
    name: imprimante
    mac: 30:CD:A7:32:8A:57

  - ip: 10.27.0.9
    name: ipcam-wifi
    mac: 48:02:2A:47:84:58

  - ip: 10.27.0.10
    name: macsly
    mac: 20:C9:D0:45:F2:57

  - ip: 10.27.0.11
    name: air-de-sorina
    mac: 84:38:35:67:86:6C

  - ip: 10.27.0.30
    name: ipad-de-sososly
    mac: 60:D9:C7:D0:8A:A8

  - ip: 10.27.0.31
    name: iphone-de-daniele
    mac: 04:F7:E4:40:3B:48

  - ip: 10.27.0.32
    name: iphone-de-soso
    mac: 7C:01:91:5C:AF:EB

  - ip: 10.27.0.37
    name: iphone-de-marie
    mac: C8:85:50:9F:2E:7C

  - ip: 10.27.0.33
    name: iphone-de-sly
    mac: 2C:33:61:A1:87:1E

  - ip: 10.27.0.34
    name: kindle-de-sly
    mac: 10:AE:60:AB:B5:5D

  - ip: 10.27.0.35
    name: iphone-de-daniele
    mac: 18:AF:61:D6:2E:E0

  - ip: 10.27.0.36
    name: orange-nura-sly
    mac: 8C:99:E6:5F:8C:F4

  - ip: 10.27.0.50
    name: thermostat
    mac: 70:EE:50:03:24:F4

  - ip: 10.27.0.51
    name: station-netatmo
    mac: 70:ee:50:01:14:80

  - ip: 10.27.0.52
    name: balance
    mac: 00:24:E4:28:01:26

  - ip: 10.27.0.53
    name: nest-cam
    mac: 18:B4:30:4E:AC:BD

  - ip: 10.27.0.54
    name: Philips-hue
    mac: 00:17:88:2A:E7:76

  - ip: 10.27.0.100
    name: pi-gw
    mac: B8:27:EB:15:E5:A0

  - ip: 10.27.0.188
    name: salon
    mac: B8:27:EB:D1:8E:10

  - ip: 10.27.0.191
    name: chambre
    mac: D8:EB:97:1B:E2:8B

  - ip: 10.8.0.14
    name: partoo.priv

  - ip: 10.8.0.1
    name: gonzo.priv

  - ip: 10.8.0.50
    name: elk.priv

  - ip: 10.8.0.54
    name: pasteque.escale-biere.com

  - ip: 10.27.0.10
    name: dev.escale-biere.com
